### ISSUE TITLE
Incompatibility with Custom Favicon

### ISSUE THREAD

**Issue by SeLLeRoNe** [custom-cards/favicon-counter#2]
Hi there,
First of all, thanks for the plugin!

Today I was messing around with the "Favicon Changer" integration and I noticed that conflicts with this plugin.

Basically, if I select a different icon, the favicon counter plugin will re-load the default one to apply the counter, after HA have already loaded the custom one, this way the custom one will appear about 1 second to then change again to the standard one.

Would be possible to integrate some kind of check for the custom favicon config and use that as favicon if present?

Thanks
Andrea

**Comment by ludeeus** [comment]
https://github.com/custom-cards/favicon-counter/releases/tag/1.0.0
