### ISSUE TITLE
Deleted plugin but somehow persisted

### ISSUE THREAD

**Issue by dooz127** [custom-cards/favicon-counter#3]
I got thousands of these errors:

`http://IP_ADDRESS:8123/community_plugin/favicon-counter/favicon-counter.js:16:26 Uncaught SecurityError: Blocked a frame with origin "http://IP_ADDRESS:8123" from accessing a cross-origin frame.`

I tried updating configuration.yaml to add:

```yaml
http:
  cors_allowed_origins:
    - http://IP_ADDRESS:8123
```  

This still didn't work so I tried removing the plugin from lovelace resources, deleting the plugin, deleting the HACS integration, clearing my browser cache handful of times, purging my Cloudflare cache, restarting HA and NGINX dozens of times but still see this error! Is there another location I need to delete the config for this plugin?

**Comment by ludeeus** [comment]
No, removing from Lovelace is enough.

**Comment by dooz127** [comment]
Stopped getting this error this afternoon. Not sure why I was seeing it even after all the steps I took (e.g., removing from lovelace yaml, removing hacs integration, clearing browser cache, purging cloudflare cache, rebuilding HA docker, etc.).

**Comment by maykar** [comment]
There's a good chance that you had another device, window, or tab open to HA that had not been refreshed.
